### ISSUE TITLE
Add support for retrieving the pattern names

### ISSUE THREAD

**Issue by bruceg** [daschl/grok#16]
With regex patterns, it is possible to ask the compiled pattern object for a list of all named captures via `Regex::capture_names`. It would be useful to ask a compiled `grok` pattern for the same kind of data.

Ref: https://docs.rs/regex/1.1.7/regex/struct.Regex.html#method.capture_names

**Comment by daschl** [comment]
After long last! Will be in 2.0.0 soon.

**Comment by daschl** [comment]
2.0.0 is released, want to try it out?
